### PR TITLE
Fancier start

### PR DESCRIPTION
**Pull request by jponge**
A fancier main and start

### CODE REVIEW

**Comment by katheris** [comment]
This looks awesome! Love the rocket. However we need to make sure we are using vert.x 4.0.0 for it to work and need to resolve the dependency issue.

**Comment by katheris** [comment]
@jponge I'll just fix the conflicts as I go through the PRs to merge if you're happy for me to do that?

**Comment by jponge** [comment]
Yes please you can do that.

**Comment by jponge** [comment]
@jponge Note that all PRs were based on top of each other, so you can easily rebase to resolve conflicts. I don't know how much you want to merge, but it should be smooth by rebasing.

**Comment by katheris** [comment]
@jponge Yes we are hoping to get them sorted today. Grace isn't as familiar with rebase as me so we are getting together today for me to step her through it. We've been slowed down by wifi issues on Grace's end!

**Comment by GraceJansen** [comment]
@jponge yes sorry for the delay, it's been hectic in the office for us with everything that's going on and my wifi outages at home haven't helped. Hopefully after our call today we should be able to get through them much quicker.

**Comment by jponge** [comment]
No worries, we’re all going through unusual times.

**Pull request merged**
