### PR TITLE
feat: upgrade Java dependencies

### PR DESCRIPTION
**Pull request by trevor-dolby-at-ibm-com**
Updates Java dependencies to latest available level.

jackson-databind is left at 2.16.1 instead of the very latest 2.18.1 because vertx-dependencies 4.5.10 pulls in 2.16.1. 
Note that 2.16.1 is not flagged as having security vulnerabilities at https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind so the upgrade to 2.18.1 is not critical at this point.

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

## Checklist
- [x] Automated tests exist
- [x] Documentation exists [link]()
- [x] Local unit tests performed
- [x] Sufficient logging/trace
- [x] Desired commit message set as PR title and commit description set above

### CODE REVIEW

**Review by ajborley — APPROVED** [review]

**Comment by Kartikey-Mishra1** [comment]
@neeraj-laad can you please review this PR.

**Review by neeraj-laad — APPROVED** [review]
LGTM, the checks on the PR are not passing. @trevor-dolby-at-ibm-com please can you address those?

**Comment by trevor-dolby-at-ibm-com** [comment]
Looks like it's related to node versions; will take a look.

**Comment by trevor-dolby-at-ibm-com** [comment]
Looks like node 20 works with the expected commit messages; it's probably worth running the actions again to see if the changes help.

**Comment by neeraj-laad** [comment]
@trevor-dolby-at-ibm-com the workflow still fails but it is much better at showing what is wrong. Can you take a look now and fix?

**Comment by tdolby-at-uk-ibm-com** [comment]
@neeraj-laad That's looking better as you say, and I think it's complaining about my squash commit message and nothing to do with code as such; I've added another commit with less text in the hope it works that way.

**Comment by neeraj-laad** [comment]
That worked. Thanks @trevor-dolby-at-ibm-com

**Comment by neeraj-laad** [comment]
@trevor-dolby-at-ibm-com I had created a release using your changes but I could not run the app locally and saw these errors:

```
  │  ~/Workspaces/starter  java -Dproperties_path=kafka.properties -jar demo-all.jar                                            INT ✘ │ 46s  │ 13:15:29 
2024-11-15 13:15:36,762 INFO [vert.x-eventloop-thread-0] kafka.vertx.demo.Main - Application version: 1.1.4
2024-11-15 13:15:36,897 INFO [vert.x-eventloop-thread-2] kafka.vertx.demo.WebSocketServer - 🚀 WebSocketServer started
2024-11-15 13:15:37,037 INFO [vert.x-eventloop-thread-1] kafka.vertx.demo.PeriodicProducer - 🚀 PeriodicProducer started
2024-11-15 13:15:37,038 INFO [vert.x-eventloop-thread-0] kafka.vertx.demo.Main - ✅ Application started in 371ms
2024-11-15 13:15:43,400 INFO [vert.x-eventloop-thread-1] kafka.vertx.demo.PeriodicProducer - Producing Kafka records
2024-11-15 13:15:48,674 ERROR [vert.x-eventloop-thread-2] io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: no null address accepted
	at java.base/java.util.Objects.requireNonNull(Objects.java:235)
	at io.vertx.core.eventbus.impl.EventBusImpl.createMessage(EventBusImpl.java:253)
	at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:118)
	at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:113)
	at kafka.vertx.demo.WebSocketServer.lambda$handleProduceSocket$7(WebSocketServer.java:126)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:177)
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.execute(HandlerRegistration.java:137)
	at io.vertx.core.eventbus.impl.DeliveryContextBase.next(DeliveryContextBase.java:80)
	at io.vertx.core.eventbus.impl.DeliveryContextBase.dispatch(DeliveryContextBase.java:43)
	at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:98)
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:183)
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:168)
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:49)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

So I deleted the release and tag to make sure everything works before we publish a release. Did you notice any such issues in your testing locally?

**Pull request merged**
