### PR TITLE
fix: release workflow trigger

### PR DESCRIPTION
**Pull request by matthew-chirgwin**
## Status
**READY**

Contributes to: #30

### Commit Message Title
* When opening this PR, the raiser should set the title of this PR to the first line of their desired commit message, e.g:
```
fix: release workflow trigger
```
* The reviewer should ensure that the first commit message field is of this form when performing the `squash and merge` from this page.

### Commit Message Description
```
- updates release workflow to trigger on matching tag format on master
branch only

Contributes to: #30

Signed-off-by: Matthew Chirgwin <chirmatt@uk.ibm.com>
```
* The reviewer should copy the above text into the extended description field when performing the `squash and merge` from this page.

### CODE REVIEW

**Comment by matthew-chirgwin** [comment]
And the tag (created in error) by the workflow can be removed by running the following commands:

```
git tag -l
git tag -d refs/heads/master
git push origin :refs/tags/refs/heads/master
```

**Comment by katheris** [comment]
@matthew-chirgwin happy for me to merge this?

**Comment by matthew-chirgwin** [comment]
> @matthew-chirgwin happy for me to merge this?

Yes please! Would you like me to run the mentioned tag commands as well, or would you like to do it?

**Comment by katheris** [comment]
I've deleted the tag via the UI

**Pull request merged**
